const GET_FETCHING_DATA_USERS = "GET_FETCHING_DATA_USERS";
const GET_ALL_USERS = "GET_ALL_USERS";
const GET_USER_BY_ID = "GET_USER_BY_ID";
const SET_DATA_USER = "SET_DATA_USER";

export {
   GET_USER_BY_ID,
   GET_FETCHING_DATA_USERS,
   GET_ALL_USERS,
   SET_DATA_USER
};
